### ISSUE TITLE
Add `react/forbid-prop-types` rule

### ISSUE THREAD

**Issue by Zeboch** [jobteaser/eslint-config-jobteaser#18]
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/forbid-prop-types.md

This will allow to force the use of `shape` or `arrayOf` to be more precise than `object` and `array`.

**Comment by royneau-jt** [comment]
👍

**Comment by happypoulp** [comment]
Looks nice, the more precise we can be in propTypes, the better. Could be used as a warning initially, to handle legacy gracefully?

**Comment by csaunier** [comment]
:+1:
