### ISSUE TITLE
Add `no-typos` rule

### ISSUE THREAD

**Issue by Zeboch** [jobteaser/eslint-config-jobteaser#20]
To avoid classic typo with React.

https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-typos.md

**Comment by csaunier** [comment]
:+1:

**Comment by happypoulp** [comment]
👍Looks very useful, especially for static props like propTypes & defaultProps for which a typo might not be revealed during development & review (if not checking for eventual warning in console).
